### Login ###
# @name login 
POST http://localhost:8000/auth/login
Content-Type: application/json
accept: application/json
 
{
  "email": "edivalmitt@gmail.com",
  "senha": "123"
}

####
@TOKEN = {{login.response.body.$.token}}

### Create ###   
POST http://localhost:8000/hd
Content-Type: application/json  
accept: application/json 
Authorization: Bearer {{TOKEN}} 

{
  "nome": "HD 1",
  "descricao": "HD XLZ",
  "status": "True",
  "path" : "/home/edival/TRABALHO/"
}

### Update ### 
PUT http://localhost:8000/hd/cec27821-9b5b-41fe-8d25-0010a4c36ba3
Content-Type: application/json
accept: application/json 
Authorization: Bearer {{TOKEN}} 
 
{
  "nome": "Empresa 45",
  "email": "empresa45@gmail.com",
  "cnpj": "12345645612",
  "status": "True"
}

### Listar ###  
GET http://localhost:8000/hd
Content-Type: application/json
accept: application/json 
Authorization: Bearer {{TOKEN}}

### Pegar ###  
GET http://localhost:8000/hd/b162c6e3-9a82-4484-aa6b-7a933e1c5818
Content-Type: application/json
accept: application/json
Authorization: Bearer {{TOKEN}}

### Excluir ### 
DELETE http://localhost:8000/hd/0092eac9-6946-497b-a6a4-010d651f4274
Content-Type: application/json
accept: application/json
Authorization: Bearer {{TOKEN}}

